### ISSUE TITLE
Corrupted ht_bert_v3.tar.gz file

### ISSUE THREAD

**Issue by vageeshSaxena** [tudou0002/NameExtractor#7]
@javinator48 Is it possible that the ht_bert_v3.tar.gz file is corrupted? 

I see that the file contains ASCII text, and when I try to uncompress it using tar -xzvf ht_bert_v3.tar.gz on Python 3.7 Linux machine, I get the following:

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by javinator48** [comment]
Hello, @vageeshSaxena  thank you for raising this concern. Yes, I think you're right.  I also had issues at first trying to directly unzip the file in my terminal as you have described.  However, I believe I found a workaround for this issue by downloading the file to my computer and unzipping it locally. I am using a Macbook and used an app called "Archive Utility" to open and unzip the file. It worked for me so I think it should also work for you as well. Thank you for your understanding and feel free to ask again if you continue to have issues. 

Thanks, 

Javin 
<img width="262" alt="Screen Shot 2023-05-29 at 4 53 11 PM" src="https://github.com/tudou0002/NEAT/assets/46199601/f7351d3c-3ab2-4583-97fa-2dc3dce1e5a8">
